---
- name: Delete a resource group
  hosts: localhost
  connection: local
  become: False
  gather_facts: False

  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: AnsiTowerWinRG25
        force_delete_nonempty: true
        state: absent
