---
- name: Create Azure VM
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars:
    location: westus
    resource_group: AnsibleCredentialstest
        
  tasks:
  - name: Create a secret
    azure_rm_keyvaultsecret:
      resource_group: AnsibleCredentialstest
      secret_name: MySecrettest
      secret_value: KmdjKol80&aswedfNjHfi&3
      keyvault_uri: https://testcredentails.vault.azure.net/
      tags:
          testing: testing
          delete: never
