---
- name: Install IIS (Web-Server and Web-Common-Http)
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: absent
        include_sub_features: yes
        include_management_tools: yes
