---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Install IIS web server
    win_feature:
       name: Web-Server
       state: present
       restart: yes
       include_sub_features: yes
       include_management_tools: yes
       
