---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: servername
  remote_user: username
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
    
    
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: servername
  remote_user: username
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
