---
- name: This sets up an httpd webserver
  hosts: all
  tasks:

  - name: authenticate with a Vault app role 
    set_fact: 
      vault_auth: "{{ lookup('hashi_vault', 'secret=eait-se-ansibletower-test/secrets/kv/awxtestlinuxvmpath auth_method=approle role_id=5ba892e7-0c2e-1ca2-d947-6cf87e0801a4 secret_id=92c394d0-61cf-cf07-354f-4e15b6daabf4 url=https://test.ess.ea.com')}}"
 
  - name: take raw return json and convert to object 
    set_fact: 
      vault_auth: "{{ vault_auth['_raw'] | from_json }}"
    
  - debug: 
      var: "{{ vault_auth.auth.client_token }}"
  - name: Install apache packages
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    service:
      name: httpd
      state: started
